### PR TITLE
[WiP] There is a test failing after merge PR#56 and PR#56

### PR DESCRIPTION
**Pull request by recena**
- [x] Fixed typos
- [x] Solved a failed test `EnvInjectJobPropertyTest#shouldNotInjectVariablesIfPropertyIsDisabled`

### CODE REVIEW

**Comment by recena** [comment]
@reviewbybees Could you review these changes? Specially, @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Yes, that's why I've recommended to run these tests before merging your PR.

:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Comment by recena** [comment]
@oleg-nenashev I runned the tests before merge without problems.

**Pull request merged**
