### PR TITLE
Cleanup deprecated code for non-deprecated equivalent

### PR DESCRIPTION
**Pull request by res0nance**
Do some misc cleaning around the codebase. Functionally equivalent to existing behaviour.

### CODE REVIEW

**Comment by marktheunissen** [comment]
@res0nance @oleg-nenashev We encountered the following error preventing Jenkins from starting, that I believe can be traced to this pull request:

```
hudson.util.HudsonFailedToLoad: java.lang.NoSuchMethodError: jenkins.model.Jenkins.get()Ljenkins/model/Jenkins;
    at hudson.WebAppMain$3.run(WebAppMain.java:236)
Caused by: java.lang.NoSuchMethodError: jenkins.model.Jenkins.get()Ljenkins/model/Jenkins;
    at org.jenkinsci.plugins.envinject.EnvInjectComputerListener.isActiveSlave(EnvInjectComputerListener.java:167)
    at org.jenkinsci.plugins.envinject.EnvInjectComputerListener.onOnline(EnvInjectComputerListener.java:140)
    at jenkins.model.Jenkins.<init>(Jenkins.java:884)
    at hudson.model.Hudson.<init>(Hudson.java:85)
    at hudson.model.Hudson.<init>(Hudson.java:81)
    at hudson.WebAppMain$3.run(WebAppMain.java:227)
```
Screenshot 2019-10-24 at 14 16 29

**Comment by res0nance** [comment]
@marktheunissen Could you file a jira ticket with the details, including which version of jenkins you are running. Since the get function has existed since `2.98` and this plugin requires `2.138`

**Comment by marktheunissen** [comment]
@res0nance It's our fault for using this plugin on an older unsupported version of Jenkins, I think we'll have to pin the old version. Thanks anyway.

**Comment by oleg-nenashev** [comment]
There should be compatibility warnings if you try to upgrade on the old
version

**Pull request merged**
