### PR TITLE
Refactoring (UX): Hide  options from the global EnvInject configuration

### PR DESCRIPTION
**Pull request by oleg-nenashev**
The change moves both security options to the Advanced section

@reviewbybees

### CODE REVIEW

**Comment by recena** [comment]
@oleg-nenashev I'd include as part of this PR other changes related to forms. For example, use the field order in **Prepare an build environment** and **Inject environment variables to the build process**.

**Comment by oleg-nenashev** [comment]
I'd keep the change separately. This one is just a minor refactoring of #57 's layouts

**Comment by recena** [comment]
@oleg-nenashev up to you. You can ignore my proposal.

**Comment by oleg-nenashev** [comment]
@recena 
> up to you. You can ignore my proposal.

I don't ignore it. I just want to fix it as another issue later. https://issues.jenkins-ci.org/browse/JENKINS-30174 BTW

**Comment by recena** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
Thanks Manuel!

@reviewbybees done

**Comment by recena** [comment]
@oleg-nenashev If you want, I can work on [JENKINS-30174](https://issues.jenkins-ci.org/browse/JENKINS-30174)

**Pull request merged**
