### PR TITLE
[FIXED JENKINS-32693] - Fix BuildCauseRetriever when AbstractBuild has Null CauseAction

### PR DESCRIPTION
**Pull request by paul-schwendenman**
Fixes the issue mentioned in https://groups.google.com/forum/#!topic/jenkinsci-dev/keV6a_YtzD0

### CODE REVIEW

**Comment by rsandell** [comment]
:+1:

**Comment by oleg-nenashev** [comment]
Looks good to me.
It would be great to have an issue for it. I'll create it before merge

**Comment by oleg-nenashev** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-32693

**Comment by paul-schwendenman** [comment]
Thanks! Sorry, I wasn't able to create an issue (it said something about spam and suggested I mention the issue on the google group)

**Pull request merged**
