### PR TITLE
Bug/findbugs nonnull info null

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just a leftover from #103 

@reviewbybees @recena @rsandell @abayer

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Contains another commit since I've pushed master after creating the PR, but should be safe

**Comment by recena** [comment]
🐝

**Comment by abayer** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done
Merging as a maintainer

**Pull request merged**
