### PR TITLE
[FIXED JENKINS-38607] - Add explicit compatibility notice for the JENKINS-31573 change

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Also updates maven-hpi-version to the version declared in POM

* https://issues.jenkins-ci.org/browse/JENKINS-31573
* https://issues.jenkins-ci.org/browse/JENKINS-38607

@reviewbybees @rsandell @jenkinsci/code-reviewers

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Well, I didn't know jelly file check is somehow related to maven-hpi-plugin

screen shot 2016-09-30 at 13 45 17

**Comment by abayer** [comment]
:bee:

**Comment by recena** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
@reviewbybees done

Going forward as a maintainer since users may have scheduled updates to the weekend

**Pull request merged**
